# Generated by Django 2.0.3 on 2018-03-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=256)),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error', models.CharField(max_length=256)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Black', models.IntegerField()),
                ('White', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Robot'),
        ),
        migrations.AddField(
            model_name='active',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Robot'),
        ),
        migrations.AddField(
            model_name='action',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Robot'),
        ),
    ]
